apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: gateway-app
    spec:
      containers:
        - name: poc-node
          image: kong/kong-gateway:3.3.0.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: gateway-env-secret
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: kong-config
              mountPath: /etc/kong/
      volumes:
        - name: kong-config
          configMap:
            name: kong-config